datasets:
  ST131: "config/datasets/ST43.txt"

guide-strain:
  ST131: "NZ_JAOSFD010000001"

pangraph:
  kernel-options:
    asm20-100-5: "--circular -k minimap2 -s 20 -a 100 -b 5"
  polish-options: "-c"

backbone-joints:
  len-thr: 500