datasets:
  ST131_ABC:
    chromosomes: "config/datasets/ST131_ABC/chromosomes.txt"
    excluded: "config/datasets/ST131_ABC/excluded.txt"
    plasmids: "config/datasets/ST131_ABC/plasmids.json"
    metadata: "config/datasets/ST131_ABC/metadata.csv"
    guide-strain: "NZ_CP096110.1"
  # ST131:
  #   chromosomes: "config/datasets/ST131_refseq/chromosomes.txt"
  #   excluded: "config/datasets/ST131_refseq/excluded.txt"
  #   metadata: "config/datasets/ST131_refseq/metadata.csv"
  #   guide-strain: "NZ_JAOSFD010000001"
  # ST131_full:
  #   chromosomes: "config/datasets/ST131_full/chromosomes.txt"
  #   excluded: "config/datasets/ST131_full/excluded.txt"
  #   plasmids: "config/datasets/ST131_full/plasmids.json"
  #   metadata: "config/datasets/ST131_full/metadata.csv"
  #   guide-strain: "NC_013654.1"

pangraph:
  kernel-options:
    asm20-100-5: "--circular -k minimap2 -s 20 -a 100 -b 5 -l 100"
  polish-options: "-c"

backbone-joints:
  len-thr: 500
  build-opt: "-k minimap2 -s 20 -a 100 -b 5 -l 100"
  polish-opt: "-c"

mlst_schemes:
  - "ecoli"
  - "ecoli_achtman_4"

allele-files:
  fimH: "config/utils/alleles/fimH.fa.gz"
  fimH_eb: "config/utils/alleles/b4320.fa.gz"
  gyrA_eb: "config/utils/alleles/b2231.fa.gz"
  parC_eb: "config/utils/alleles/b3019.fa.gz"
  FIA: "config/utils/alleles/FIA.fa.gz"
  FIB: "config/utils/alleles/FIB.fa.gz"
  FIC: "config/utils/alleles/FIC.fa.gz"
  FII: "config/utils/alleles/FII.fa.gz"
  FIIK: "config/utils/alleles/FIIK.fa.gz"
  FIIS: "config/utils/alleles/FIIS.fa.gz"
  FIIY: "config/utils/alleles/FIIY.fa.gz"

chr_alleles:
  - fimH
  - fimH_eb
  - gyrA_eb
  - parC_eb

plsm_alleles:
  - FIA
  - FIB
  - FIC
  - FII
  - FIIK
  - FIIS
  - FIIY

resistance:
  id_threshold: 0.95