datasets:
  ST131: "config/datasets/ST43.txt"

excluded:
  ST131: "config/datasets/ST43_excluded.txt"

metadata:
  ST131: "config/datasets/ST43_metadata_raw.csv"

guide-strain:
  ST131: "NZ_JAOSFD010000001"

pangraph:
  kernel-options:
    asm20-100-5: "--circular -k minimap2 -s 20 -a 100 -b 5 -l 100"
  polish-options: "-c"

backbone-joints:
  len-thr: 500
  build-opt: "-k minimap2 -s 20 -a 100 -b 5 -l 100"
  polish-opt: "-c"

mlst_schemes:
  - "ecoli"
  - "ecoli_achtman_4"

alleles:
  fimH: "config/utils/alleles/fimH.fa.gz"
  fimH_eb: "config/utils/alleles/b4320.fa.gz"
  gyrA_eb: "config/utils/alleles/b2231.fa.gz"
  parC_eb: "config/utils/alleles/b3019.fa.gz"