resistance:
	conda run -n bioinfo python 1_resistance.py \
	--plasmid_json ../../config/datasets/ST131_full/plasmids.json \
	--resistance_tsv ../../results/ST131_full/plasmids/resistance/ncbi_summary.txt \
	--threshold_id 0.95 \
	--out_csv 'test.csv'